### ISSUE TITLE
set up unit test for Rally Extension aka Attention Stream

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally#428]
Trying to get unit tests working for attention stream extension, Glean is causing problems... this seems familiar, didn't we hit an issue with the cloud functions where we had to switch to ES modules, because Glean doesn't export CommonJS modules in the way the bundler wanted? I wonder if that's the issue I'm hitting here, it's like the import statements aren't getting switched to require and Jest isn't totally ES-module-compatible yet I don't think:
```
Details:

    /Users/roberthelmer/src/rally/extensions/attention-stream/node_modules/@mozilla/glean/dist/plugins/encryption.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { CompactEncrypt, importJWK, calculateJwkThumbprint } from "jose";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      13 | import { Rally, RunStates } from "@mozilla/rally-sdk";
      14 |
    > 15 | import PingEncryptionPlugin from "@mozilla/glean/plugins/encryption";
         | ^
      16 | import Glean, {
      17 |   Uploader,
      18 |   UploadResult,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/background.ts:15:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.687s
```

**Comment by rhelmer** [comment]
Jest has experimental (due to it being experimental in Node) support for modules: https://jestjs.io/docs/ecmascript-modules

IIRC this is what we do for our cloud functions, we could consider doing the same here, if only for tests.
